// <auto-generated />
using System;
using ManagmentStoreService.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManagmentStoreService.Migrations
{
    [DbContext(typeof(ManagStoreDbContext))]
    [Migration("20250730084713_Updates")]
    partial class Updates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.17");

            modelBuilder.Entity("ManagmentStoreService.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ManagmentStoreService.Models.HeadphonesEntities.CodecType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CodecType");
                });

            modelBuilder.Entity("ManagmentStoreService.Models.HeadphonesEntities.Headphones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VariantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("VariantId");

                    b.ToTable("Headphones");
                });

            modelBuilder.Entity("ManagmentStoreService.Models.HeadphonesEntities.HeadphonesImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMain")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HeadphonesImages");
                });

            modelBuilder.Entity("ManagmentStoreService.Models.HeadphonesEntities.HeadphonesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("HeadphonesModels");
                });

            modelBuilder.Entity("ManagmentStoreService.Models.HeadphonesEntities.HeadphonesSpec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodecId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FrequencyRangeHz")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsWireless")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CodecId");

                    b.ToTable("HeadphonesSpecs");
                });

            modelBuilder.Entity("ManagmentStoreService.Models.HeadphonesEntities.HeadphonesVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpecId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.HasIndex("SpecId");

                    b.ToTable("HeadphonesVariants");
                });

            modelBuilder.Entity("ManagmentStoreService.Models.HeadphonesEntities.HeadphonesVariantImage", b =>
                {
                    b.Property<int>("VariantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("VariantId", "ImageId");

                    b.HasIndex("ImageId");

                    b.ToTable("HeadphonesVariantImages");
                });

            modelBuilder.Entity("ManagmentStoreService.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LocationId");

                    b.HasIndex("OrderId");

                    b.HasIndex("StatusId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("ManagmentStoreService.Models.ItemStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ItemsStatuses");
                });

            modelBuilder.Entity("ManagmentStoreService.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("ManagmentStoreService.Models.Manufacturers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("ManagmentStoreService.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDelivery")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PaymentAmountDelivery")
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ManagmentStoreService.Models.PhoneEntities.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VariantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("VariantId");

                    b.ToTable("Phones");
                });

            modelBuilder.Entity("ManagmentStoreService.Models.PhoneEntities.PhoneImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMain")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PhoneImages");
                });

            modelBuilder.Entity("ManagmentStoreService.Models.PhoneEntities.PhoneModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("PhoneModels");
                });

            modelBuilder.Entity("ManagmentStoreService.Models.PhoneEntities.PhoneSpec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("CameraMp")
                        .HasColumnType("REAL");

                    b.Property<float>("DisplayIn")
                        .HasColumnType("REAL");

                    b.Property<int>("RamGb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StorageGb")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "StorageGb", "RamGb", "DisplayIn", "CameraMp" }, "IX_UniquePhoneSpec")
                        .IsUnique();

                    b.ToTable("PhoneSpecs");
                });

            modelBuilder.Entity("ManagmentStoreService.Models.PhoneEntities.PhoneVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpecId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.HasIndex("SpecId");

                    b.ToTable("PhoneVariants");
                });

            modelBuilder.Entity("ManagmentStoreService.Models.PhoneEntities.PhoneImage", b =>
                {
                    b.Property<int>("VariantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("VariantId", "ImageId");

                    b.HasIndex("ImageId");

                    b.ToTable("PhoneVariantImages");
                });

            modelBuilder.Entity("ManagmentStoreService.Models.HeadphonesEntities.Headphones", b =>
                {
                    b.HasOne("ManagmentStoreService.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManagmentStoreService.Models.HeadphonesEntities.HeadphonesVariant", "Variant")
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("ManagmentStoreService.Models.HeadphonesEntities.HeadphonesModel", b =>
                {
                    b.HasOne("ManagmentStoreService.Models.Manufacturers", "Manufacturers")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturers");
                });

            modelBuilder.Entity("ManagmentStoreService.Models.HeadphonesEntities.HeadphonesSpec", b =>
                {
                    b.HasOne("ManagmentStoreService.Models.HeadphonesEntities.CodecType", "Codec")
                        .WithMany()
                        .HasForeignKey("CodecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Codec");
                });

            modelBuilder.Entity("ManagmentStoreService.Models.HeadphonesEntities.HeadphonesVariant", b =>
                {
                    b.HasOne("ManagmentStoreService.Models.HeadphonesEntities.HeadphonesModel", "Model")
                        .WithMany("Variants")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManagmentStoreService.Models.HeadphonesEntities.HeadphonesSpec", "Spec")
                        .WithMany()
                        .HasForeignKey("SpecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");

                    b.Navigation("Spec");
                });

            modelBuilder.Entity("ManagmentStoreService.Models.HeadphonesEntities.HeadphonesVariantImage", b =>
                {
                    b.HasOne("ManagmentStoreService.Models.HeadphonesEntities.HeadphonesImage", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManagmentStoreService.Models.HeadphonesEntities.HeadphonesVariant", "Variant")
                        .WithMany("VariantImages")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("ManagmentStoreService.Models.Item", b =>
                {
                    b.HasOne("ManagmentStoreService.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManagmentStoreService.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("ManagmentStoreService.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId");

                    b.HasOne("ManagmentStoreService.Models.ItemStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId");

                    b.Navigation("Category");

                    b.Navigation("Location");

                    b.Navigation("Order");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("ManagmentStoreService.Models.Order", b =>
                {
                    b.HasOne("ManagmentStoreService.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("ManagmentStoreService.Models.PhoneEntities.Phone", b =>
                {
                    b.HasOne("ManagmentStoreService.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManagmentStoreService.Models.PhoneEntities.PhoneVariant", "Variant")
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("ManagmentStoreService.Models.PhoneEntities.PhoneModel", b =>
                {
                    b.HasOne("ManagmentStoreService.Models.Manufacturers", "Manufacturers")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturers");
                });

            modelBuilder.Entity("ManagmentStoreService.Models.PhoneEntities.PhoneVariant", b =>
                {
                    b.HasOne("ManagmentStoreService.Models.PhoneEntities.PhoneModel", "Model")
                        .WithMany("PhoneVariants")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManagmentStoreService.Models.PhoneEntities.PhoneSpec", "Spec")
                        .WithMany()
                        .HasForeignKey("SpecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");

                    b.Navigation("Spec");
                });

            modelBuilder.Entity("ManagmentStoreService.Models.PhoneEntities.PhoneImage", b =>
                {
                    b.HasOne("ManagmentStoreService.Models.PhoneEntities.PhoneImage", "Image")
                        .WithMany("VariantImages")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManagmentStoreService.Models.PhoneEntities.PhoneVariant", "Variant")
                        .WithMany("VariantImages")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("ManagmentStoreService.Models.HeadphonesEntities.HeadphonesModel", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("ManagmentStoreService.Models.HeadphonesEntities.HeadphonesVariant", b =>
                {
                    b.Navigation("VariantImages");
                });

            modelBuilder.Entity("ManagmentStoreService.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ManagmentStoreService.Models.PhoneEntities.PhoneImage", b =>
                {
                    b.Navigation("VariantImages");
                });

            modelBuilder.Entity("ManagmentStoreService.Models.PhoneEntities.PhoneModel", b =>
                {
                    b.Navigation("PhoneVariants");
                });

            modelBuilder.Entity("ManagmentStoreService.Models.PhoneEntities.PhoneVariant", b =>
                {
                    b.Navigation("VariantImages");
                });
#pragma warning restore 612, 618
        }
    }
}
